baseURL = 'https://parth-choudhary.github.io/'
languageCode = 'en-us'
title = 'Parth Choudhary'

[params]
  description = 'Personal website where I share my thoughts and projects.'
  author = 'Parth Choudhary'
  github = 'parth-choudhary'
  email = 'parth.choudhary@gmail.com'

[params.hero]
  enabled = true
  title = "Hi, I'm Parth"
  subtitle = "I build things and write about my experiences"
  show_socials = true

[params.about]
  enabled = true
  
[params.projects]
  enabled = true

[params.blog]
  enabled = true
  paginate = 5
